apiVersion: v1
kind: Pod
metadata: 
 lables: 
   name: myapp
   env: prod
 annotations:
  description: "test pod"
 name: nginx
spec: 
  containers:
  - name: nginx
    image: nginx:latest 
    ports:
    - containerPort: 80
  restartPolicy: Never
  lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo 'PostStart'"]
      preStop:
        exec:
          command: ["/bin/sh", "-c", "echo 'PreStop'"]